#!/bin/sh
lock() {
    scrot /tmp/screen_locked.png
    convert /tmp/screen_locked.png -scale 5% -scale 2000% /tmp/screen_locked.png
    i3lock -fed -i /tmp/screen_locked.png
    # sleep 60; pgrep i3lock && xset dpms force off
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
