#!/bin/sh

OVERLAY=$(shuf -n1 -e ~/.config/i3/scripts/assets/lock/*.png)
BG=/tmp/screen_locked.png
lock() {
    scrot $BG
    convert $BG -scale 5% -scale 2000% $BG
    convert $BG $OVERLAY -gravity SouthWest -composite $BG
    i3lock -fed -i $BG
    # sleep 60; pgrep i3lock && xset dpms force off
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
